--FUNCIONES
--FUNCION LOWER, UPPER ,INITCAP

SELECT LOWER(EMAIL) FROM EMPLOYEES; 
SELECT FIRST_NAME, UPPER(FIRST_NAME)  FROM EMPLOYEES; 

SELECT INITCAP('ESTO ES UNA PRUEBA') FROM DUAL;
--
SELECT FIRST_NAME FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME)='DAVID'; 

--CONCAT: CONCATENAR

SELECT CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)) FROM EMPLOYEES;

--LENGTH

SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES;

SELECT FIRST_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME)=6;

--SUBSTR(CADENA, POSICION, LONGITUD)

SELECT SUBSTR(FIRST_NAME,1,3) FROM EMPLOYEES;


SELECT SUBSTR(FIRST_NAME,3) FROM EMPLOYEES;

SELECT FIRST_NAME, SUBSTR(FIRST_NAME,LENGTH(FIRST_NAME),1) FROM EMPLOYEES;

--INSTR DEVOLVER LA POSICION QUE UNA CADENA DENTRO DE OTRA CADENA
SELECT FIRST_NAME, INSTR(FIRST_NAME,'a') FROM EMPLOYEES;
SELECT FIRST_NAME, INSTR(FIRST_NAME,'a') FROM EMPLOYEES WHERE INSTR(FIRST_NAME,'a')<>0 ;
SELECT FIRST_NAME, INSTR(LOWER(FIRST_NAME),'a') FROM EMPLOYEES WHERE INSTR(LOWER(FIRST_NAME),'a')<>0 ;
SELECT FIRST_NAME, INSTR(FIRST_NAME,'a',4) FROM EMPLOYEES;-- BUSCA  APARTIR DE LA POSICION NUMERO 4

-- LPAD RPAD

SELECT RPAD(FIRST_NAME, 20,'*') FROM EMPLOYEES;
SELECT LPAD(FIRST_NAME, 20,'*') FROM EMPLOYEES;

--REPLACE(CADENA,CADENA ORIGINAL,NUEVA)

SELECT REPLACE(FIRST_NAME, 'a','*') FROM EMPLOYEES;

--LTRIM RTRIM
SELECT 'ALBERTO      '||'PEREZ' FROM DUAL;
SELECT RTRIM('ALBERTO      ')||'PEREZ' FROM DUAL;
SELECT 'ALBERTO '||LTRIM('    PEREZ') FROM DUAL;
SELECT FIRST_NAME, RTRIM(FIRST_NAME,'m') FROM EMPLOYEES;--ELIMINA LAS M AL FINAL DE LAS LETRAS





