SELECT FIRST_NAME, LAST_NAME, SALARY AS "Salario Empleado" FROM EMPLOYEES;
--esto es un comentario
/*
otro tipo de comentario
*/
SELECT FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;

SELECT FIRST_NAME AS NOMBRE, JOB_ID AS "Tipo de Trabajo" FROM EMPLOYEES;

SELECT * FROM REGIONS;

SELECT COUNTRY_NAME AS "Nombre Pais" FROM COUNTRIES;

SELECT STREET_ADDRESS AS "dirección", CITY AS "Ciudad", STATE_PROVINCE AS "Estado" FROM LOCATIONS;

/* operadores 
+ suma
- resta
/ division
* multiplicacion
% resto
*/
SELECT FIRST_NAME, SALARY, SALARY*12 AS "SALARIO ANUAL" FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY AS "Bruto", (SALARY/100)*20 AS IMPUESTO,SALARY-(SALARY/100)*20 AS NETO FROM EMPLOYEES;

SELECT FIRST_NAME AS "Nombre", SALARY AS "Salario",SALARY*14 AS "Salario Anual" FROM EMPLOYEES;

/*
Literales(cadenas de caracter)

*/
SELECT 'NOMBRE:', FIRST_NAME FROM EMPLOYEES;
SELECT 'NOMBRE:'|| FIRST_NAME AS "Nombre Empleado" FROM EMPLOYEES;-- LAS DOS BARRAS CONCATENAN TEXTO CON FILA
SELECT 'NOMBRE: '|| FIRST_NAME || ' '||LAST_NAME AS "NOMBRE EMPLEADO" FROM EMPLOYEES; 

SELECT 'El empleado '|| FIRST_NAME || ' del departamento '|| DEPARTMENT_ID || ' tiene un salario de '|| SALARY||'.' AS DATOS FROM EMPLOYEES;

SELECT 'La calle '||STREET_ADDRESS ||' pertence a la ciudad : '||CITY ||'.' FROM LOCATIONS;

/*
TABLAS DUALES
*/
SELECT 4+3, FIRST_NAME FROM EMPLOYEES;  
SELECT 4+3, 'ES EL RESULTADO' FROM DUAL;-- DEVUELVE EL RESULTADO DE LA OPERACION SIN LA NECESIDAD DE LLAMAR UNA TABLA EN ESPECIFICO
DESC DUAL;

/*
NULOS NULL
*/
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, SALARY*COMMISSION_PCT AS "SALARIO TOTAL"  FROM EMPLOYEES;  

/*
DISTINC: BUSCA LO VALORES ELIMINANDO LOS DUPLICADOS 
*/
SELECT FIRST_NAME,DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;

SELECT DISTINCT CITY FROM LOCATIONS;

SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;
