SELECT XXXX FROM TABLA WHERE CONDICION;

SELECT * FROM EMPLOYEES 
WHERE  DEPARTMENT_ID=50;

/*
= IGUALDAD
> MAYOR 
<MENOR
>=MAYOR O IGUAL
<= MENOR O IGUAL
<>DISTINTO
*/

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY>5000;

SELECT FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID<>50;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='John';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME<>'John';

SELECT * FROM EMPLOYEES WHERE HIRE_DATE='21-06-07';--1 DE ENERO DE 4712

SELECT * FROM EMPLOYEES WHERE HIRE_DATE>'21-06-07';

SELECT * FROM EMPLOYEES WHERE HIRE_DATE<'21-06-07';
--PRACTICA
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;

SELECT CITY, STREET_ADDRESS FROM LOCATIONS WHERE COUNTRY_ID = 'US';

SELECT COUNTRY_NAME FROM COUNTRIES WHERE REGION_ID = 3;

SELECT FIRST_NAME, SALARY, MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID <> 114;

SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '01-01-2006';

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'ST_CLERK'; 

SELECT * FROM EMPLOYEES WHERE LAST_NAME = 'Smith';

/*
BETWEEN
*/
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 6000;

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-01-07' AND '01-01-09'; 

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME BETWEEN 'Douglass' AND 'Stevens';

/*
IN(V1,V2,V3)
*/
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50,60);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('SH_CLERK','ST_CLERK','ST_MAN');

--PRACTICA
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 40 AND 60;

SELECT * FROM EMPLOYEES 
WHERE HIRE_DATE BETWEEN '01-01-02' AND '01-01-04';


SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME BETWEEN 'D' AND 'G';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (30,60,90);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'PU_CLERK');

SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID IN ('UK', 'JP');

-- fin practica

--OPERADOR LIKE 

SELECT * FROM EMPLOYEES
WHERE FIRS_NAME LIKE 'J%';

SELECT *FROM EMPLOYEES WHERE 
FIRST_NAME LIKE '_e%';-- EXRESION REGULAR QUE NOS DICE QUE EL PRIMER CARACTER SEA CUALQUIER COSA, EL SEGUNDO SEA UNA e y de ahi en adelante cualquiercosa7

SELECT * FROM EMPLOYEES WHERE
FIRST_NAME LIKE '%te%';-- que encuentre una t en la mitad de la palabra 

--practica
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'J%'; 

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'S%n';

SELECT * FROM COUNTRIES WHERE COUNTRY_NAME LIKE '_r%';
 
-- fin practica

--CLAUSULA IS NULL

SELECT * FROM EMPLOYEES WHERE  COMMISSION_PCT IS NULL;

SELECT * FROM EMPLOYEES WHERE  COMMISSION_PCT IS NOT NULL;

--PRACTICA 
SELECT * FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;

SELECT FIRST_NAME, SALARY, COMMISSION_PCT ,(SALARY*COMMISSION_PCT)/100 AS "Sueldo Total" FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--FIN PRACTICA
--OPERADORES AND, OR NOT

SELECT * FROM EMPLOYEES 
WHERE SALARY>5000 AND DEPARTMENT_ID = 50;  

SELECT * FROM EMPLOYEES 
WHERE SALARY>5000 OR DEPARTMENT_ID = 50;  

SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT_ID NOT IN(50,40);

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES
WHERE SALARY > 5000 AND DEPARTMENT_ID = 50 AND HIRE_DATE > '01-01-05';

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES
WHERE SALARY > 5000 AND (DEPARTMENT_ID = 50 OR HIRE_DATE > '01-01-05');

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES
WHERE SALARY > 5000 AND DEPARTMENT_ID = 50 OR HIRE_DATE > '01-01-05';

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID, HIRE_DATE FROM EMPLOYEES
WHERE (SALARY > 5000 AND DEPARTMENT_ID = 50) OR HIRE_DATE > '01-01-05';

--Practica

SELECT FIRST_NAME, HIRE_DATE, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' AND SALARY < 6000; 

SELECT * FROM EMPLOYEES 
WHERE (DEPARTMENT_ID=50 OR DEPARTMENT_ID=80) AND SALARY > 3000;

SELECT * FROM EMPLOYEES--SIEMPRE QUE INVOLUCRE EXPRESIONES REGULARES UTILIZAR LIKE 
WHERE JOB_ID='IT_PROG' AND PHONE_NUMBER LIKE '5%' AND HIRE_DATE BETWEEN '01-01-07' AND '21-12-2007';







