SELECT XXXX FROM TABLA WHERE CONDICION;

SELECT * FROM EMPLOYEES 
WHERE  DEPARTMENT_ID=50;

/*
= IGUALDAD
> MAYOR 
<MENOR
>=MAYOR O IGUAL
<= MENOR O IGUAL
<>DISTINTO
*/

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY>5000;

SELECT FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID<>50;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='John';

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME<>'John';

SELECT * FROM EMPLOYEES WHERE HIRE_DATE='21-06-07';--1 DE ENERO DE 4712

SELECT * FROM EMPLOYEES WHERE HIRE_DATE>'21-06-07';

SELECT * FROM EMPLOYEES WHERE HIRE_DATE<'21-06-07';
--PRACTICA
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;

SELECT CITY, STREET_ADDRESS FROM LOCATIONS WHERE COUNTRY_ID = 'US';

SELECT COUNTRY_NAME FROM COUNTRIES WHERE REGION_ID = 3;

SELECT FIRST_NAME, SALARY, MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID <> 114;

SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '01-01-2006';

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'ST_CLERK'; 

SELECT * FROM EMPLOYEES WHERE LAST_NAME = 'Smith';

/*
BETWEEN
*/
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 6000;

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-01-07' AND '01-01-09'; 

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME BETWEEN 'Douglass' AND 'Stevens';

/*
IN(V1,V2,V3)
*/
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50,60);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('SH_CLERK','ST_CLERK','ST_MAN');

--PRACTICA
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 40 AND 60;

SELECT * FROM EMPLOYEES 
WHERE HIRE_DATE BETWEEN '01-01-02' AND '01-01-04';


SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME BETWEEN 'D' AND 'G';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (30,60,90);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'PU_CLERK');

SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID IN ('UK', 'JP');




